<img src="https://drive.google.com/uc?export=view&id=1Y-EIpLOigI9ycCOZRrRSFzAfuN9cxhqT" alt="Hobot Academy" width="300" height="300">

<h1 align="center"><font size="14">Hands-On Machine Learning</font></h1>
<h3 align="center"><font size="7">Session04: Pandas</font></h3>
<h3 align="center">Zahra Amini</h3>

# Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Series

In [2]:
students = ['Alice', 'Jack', None]

pd.Series(students)

0    Alice
1     Jack
2     None
dtype: object

In [3]:
#dictionary

students_course = {'Ali': 'Physics',
                   'pouria': 'Chemistry',
                   'saeed': 'English'}
s = pd.Series(students_course)
s

Ali         Physics
pouria    Chemistry
saeed       English
dtype: object

In [4]:
s.index

Index(['Ali', 'pouria', 'saeed'], dtype='object')

# DataFrame

In [5]:
record1 = pd.Series({'Name': 'Ali',
                        'Class': 'Physics',
                        'Score': 85})

record2 = pd.Series({'Name': 'pouria',
                        'Class': 'Chemistry',
                        'Score': 82})

record3 = pd.Series({'Name': 'saeed',
                        'Class': 'Biology',
                        'Score': 90})

In [6]:
df = pd.DataFrame([record1, record2, record3],
                  index=['school1', 'school2', 'school1'])

In [7]:
df

           Name      Class  Score
school1     Ali    Physics     85
school2  pouria  Chemistry     82
school1   saeed    Biology     90

# Read data

In [8]:
df = pd.read_csv("imdb_top_250_series_global_ratings.csv")

In [9]:
df

          Code                 Title     Code.1  Rating Rating Count
0    tt5491994       Planet Earth II  tt5491994     9.4      142,844
1    tt0903747          Breaking Bad  tt0903747     9.4    1,817,275
2    tt0795176          Planet Earth  tt0795176     9.4      208,191
3    tt0185906      Band of Brothers  tt0185906     9.4      460,468
4    tt7366338             Chernobyl  tt7366338     9.3      729,461
..         ...                   ...        ...     ...          ...
245  tt5249462                Erased  tt5249462     8.4       45,760
246  tt0988818               Gintama  tt0988818     8.4       11,177
247  tt7259746             Queer Eye  tt7259746     8.4       18,877
248  tt1298820  Clannad: After Story  tt1298820     8.4       11,239
249  tt0043208           I Love Lucy  tt0043208     8.4       26,622

[250 rows x 5 columns]

# Q1: What are the first/tailing 5 entries?

In [10]:
df.head(10)

        Code                        Title     Code.1  Rating Rating Count
0  tt5491994              Planet Earth II  tt5491994     9.4      142,844
1  tt0903747                 Breaking Bad  tt0903747     9.4    1,817,275
2  tt0795176                 Planet Earth  tt0795176     9.4      208,191
3  tt0185906             Band of Brothers  tt0185906     9.4      460,468
4  tt7366338                    Chernobyl  tt7366338     9.3      729,461
5  tt0306414                     The Wire  tt0306414     9.3      334,219
6  tt6769208               Blue Planet II  tt6769208     9.2       40,655
7  tt0417299   Avatar: The Last Airbender  tt0417299     9.2      307,797
8  tt2395695  Cosmos: A Spacetime Odyssey  tt2395695     9.2      121,155
9  tt0141842                 The Sopranos  tt0141842     9.2      387,781

In [11]:
df.tail()

          Code                 Title     Code.1  Rating Rating Count
245  tt5249462                Erased  tt5249462     8.4       45,760
246  tt0988818               Gintama  tt0988818     8.4       11,177
247  tt7259746             Queer Eye  tt7259746     8.4       18,877
248  tt1298820  Clannad: After Story  tt1298820     8.4       11,239
249  tt0043208           I Love Lucy  tt0043208     8.4       26,622

# Q2: What is the number of observations in the dataset?

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Code          250 non-null    object
 1   Title         250 non-null    object
 2   Code.1        250 non-null    object
 3   Rating        250 non-null    float64
 4   Rating Count  250 non-null    object
dtypes: float64(1), object(4)
memory usage: 9.9+ KB

In [13]:
# rows, columns

df.shape

(250, 5)

In [14]:
# rows

df.shape[0]

250

In [15]:
# columns

df.shape[1]

5

In [16]:
df.columns

Index(['Code', 'Title', 'Code.1', 'Rating', 'Rating Count'], dtype='object')

# Q3: How is the dataset indexed?

In [17]:
df.index

RangeIndex(start=0, stop=250, step=1)

# Q4: What is the 10th movie?

In [18]:
df.values[10][1]

'Our Planet'

In [19]:
df.values[10][[1, 3]]

array(['Our Planet', 9.2], dtype=object)

In [20]:
df.head(10)

        Code                        Title     Code.1  Rating Rating Count
0  tt5491994              Planet Earth II  tt5491994     9.4      142,844
1  tt0903747                 Breaking Bad  tt0903747     9.4    1,817,275
2  tt0795176                 Planet Earth  tt0795176     9.4      208,191
3  tt0185906             Band of Brothers  tt0185906     9.4      460,468
4  tt7366338                    Chernobyl  tt7366338     9.3      729,461
5  tt0306414                     The Wire  tt0306414     9.3      334,219
6  tt6769208               Blue Planet II  tt6769208     9.2       40,655
7  tt0417299   Avatar: The Last Airbender  tt0417299     9.2      307,797
8  tt2395695  Cosmos: A Spacetime Odyssey  tt2395695     9.2      121,155
9  tt0141842                 The Sopranos  tt0141842     9.2      387,781

# Q5: How many series have Rating=9 and Rating Count more than 100,000?

In [21]:
# delete the duplicates

df_new = df.drop_duplicates(['Title'])
df_new

          Code                 Title     Code.1  Rating Rating Count
0    tt5491994       Planet Earth II  tt5491994     9.4      142,844
1    tt0903747          Breaking Bad  tt0903747     9.4    1,817,275
2    tt0795176          Planet Earth  tt0795176     9.4      208,191
3    tt0185906      Band of Brothers  tt0185906     9.4      460,468
4    tt7366338             Chernobyl  tt7366338     9.3      729,461
..         ...                   ...        ...     ...          ...
245  tt5249462                Erased  tt5249462     8.4       45,760
246  tt0988818               Gintama  tt0988818     8.4       11,177
247  tt7259746             Queer Eye  tt7259746     8.4       18,877
248  tt1298820  Clannad: After Story  tt1298820     8.4       11,239
249  tt0043208           I Love Lucy  tt0043208     8.4       26,622

[245 rows x 5 columns]

In [22]:
df_new = df_new[['Title','Rating','Rating Count']]

In [23]:
df_new = df_new[df_new['Rating'] == 9 ]
df_new

                                 Title  Rating Rating Count
16                      The Last Dance     9.0      118,827
17                                Life     9.0       40,832
18                            Sherlock     9.0      910,868
19                   The Twilight Zone     9.0       82,522
20                     The Vietnam War     9.0       24,523
21         Batman: The Animated Series     9.0      102,514
22  Scam 1992: The Harshad Mehta Story     9.0      142,151

In [24]:
df_new[df_new['Rating Count'] > '100000'].nunique()

Title           7
Rating          1
Rating Count    7
dtype: int64

In [25]:
df_new[df_new['Rating Count'] > '100000']['Title'].nunique()

7

# Q6: Sort by Title

In [26]:
df.Title.sort_values()

# OR

# df.sort_values(by = "Title")

113                         1883
145               Adventure Time
48                        Africa
226    Alfred Hitchcock Presents
153               Anne with an E
                 ...
143                  Yellowstone
159                 Yes Minister
189          Yes, Prime Minister
139                Young Justice
233            Your Lie in April
Name: Title, Length: 250, dtype: object

In [27]:
#ascending:صعودی

df.sort_values(by = "Title", ascending=False)

           Code                      Title      Code.1  Rating Rating Count
233   tt3895150          Your Lie in April   tt3895150     8.4       28,651
139   tt1641384              Young Justice   tt1641384     8.6       41,093
189   tt0086831        Yes, Prime Minister   tt0086831     8.5       11,536
159   tt0080306               Yes Minister   tt0080306     8.5       14,817
143   tt4236770                Yellowstone   tt4236770     8.5      124,427
..          ...                        ...         ...     ...          ...
153   tt5421602             Anne with an E   tt5421602     8.5       53,857
226   tt0047708  Alfred Hitchcock Presents   tt0047708     8.4       17,289
48    tt2571774                     Africa   tt2571774     8.8       16,011
145   tt1305826             Adventure Time   tt1305826     8.5       93,443
113  tt13991232                       1883  tt13991232     8.6       61,168

[250 rows x 5 columns]

# Q7: What was the Series with the most Rating Count?

In [28]:
df.sort_values(by = "Rating Count").head(1)

         Code            Title     Code.1  Rating Rating Count
89  tt4574334  Stranger Things  tt4574334     8.7    1,139,539

In [29]:
# kamtarin

df.sort_values(by = "Rating Count", ascending = False).head(1)

          Code      Title     Code.1  Rating Rating Count
156  tt1489428  Justified  tt1489428     8.5       99,640

# Q8: What is the average rating of the series?

In [30]:
df2 = pd.read_csv("imdb_top_250_series_episode_ratings.csv")

In [31]:
df2.head()

   Unnamed: 0  Season  Episode  Rating       Code            Title
0           0       1        1     9.4  tt5491994  Planet Earth II
1           1       1        2     9.1  tt5491994  Planet Earth II
2           2       1        3     8.9  tt5491994  Planet Earth II
3           3       1        4     8.8  tt5491994  Planet Earth II
4           4       1        5     8.6  tt5491994  Planet Earth II

In [ ]:
df2.drop('Unnamed: 0',axis=1, inplace=True)

#df2 = df2.drop('Unnamed: 0')

In [ ]:
df2.head()

In [ ]:
df2.groupby('Title').mean()

In [ ]:
df_c = df2.groupby(['Title', 'Code']).mean()

In [ ]:
df_c

In [ ]:
df_c['Rating']

In [ ]:
df_c = df_c[['Rating']]
df_c

In [ ]:
df_c.rename(columns = {'Rating':'Mean Rating'}, inplace = True)

In [ ]:
df_c.head()

# Q9: What is the name of 5 First rating of the series?

In [ ]:
max_index = df2['Rating'].idxmax()

df2.iloc[max_index]["Title"]

In [ ]:
df2.sort_values(by ='Rating', ascending=False)[:5][['Title']].reset_index()

# Q10: What are the the first three characters of the series code?

In [ ]:
df['Code'].apply(lambda x : x[:3]).value_counts()

# Q11: Percentage

In [ ]:
(df['Rating'].value_counts(normalize=True) * 100).sort_values()

# Finished!